name: secure_notes
description: An Assessment For Ontik Technologies

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #State Management
  get: ^4.6.6

  #UI
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^16.3.2

  #Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  connectivity_plus: ^2.3.8

  #Secure Data
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9

  #Firebase
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  flutter_datetime_picker_plus: ^2.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_forground: "assets/appIcon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

